import json
import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

class AuditReporter:
    def __init__(self, diagnostic_data: dict, output_path: str = "./reports"):
        """
        Initializes the reporter using the AEGIS-4 nested data structure.
        """
        self.data = diagnostic_data
        self.output_path = output_path
        
        # Mapping to the new nested metadata structure
        self.model_id = self.data['model_metadata']['id']
        self.model_name = self.model_id.replace("/", "_")
        self.timestamp_str = self.data['model_metadata']['timestamp']
        self.file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        if not os.path.exists(self.output_path):
            os.makedirs(self.output_path)

    def save_json(self) -> str:
        """Saves the full audit log for integration with security systems."""
        file_path = os.path.join(self.output_path, f"audit_{self.model_name}_{self.file_timestamp}.json")
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(self.data, f, indent=4, ensure_ascii=False)
        return file_path

    def save_pdf(self) -> str:
        """Generates the official executive report in PDF using your original style."""
        file_path = os.path.join(self.output_path, f"report_{self.model_name}_{self.file_timestamp}.pdf")
        doc = SimpleDocTemplate(file_path, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        # Professional Title
        elements.append(Paragraph("SAFEQUANT-SLM: AEGIS-4 AUDIT REPORT", styles['Title']))
        elements.append(Spacer(1, 12))

        # General Information Section
        elements.append(Paragraph(f"<b>Model ID:</b> {self.model_id}", styles['Normal']))
        elements.append(Paragraph(f"<b>Audit Timestamp:</b> {self.timestamp_str}", styles['Normal']))
        elements.append(Spacer(1, 12))

        # 1. Engineering & Efficiency Metrics (Table 1)
        perf = self.data['performance_metrics']
        res = self.data['resource_metrics']
        sec = self.data['security_audit']
        
        metrics_data = [
            ["Metric Category", "Measured Value"],
            ["Security Score", f"{sec['global_score']}%"],
            ["Memory Consumption", f"{res['vram_allocated_mib']} MiB"],
            ["Inference Latency", f"{perf['latency_sec']}s"],
            ["Throughput", f"{perf['throughput_tps']} tokens/sec"]
        ]
        
        t1 = Table(metrics_data, colWidths=[200, 200])
        t1.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ]))
        
        elements.append(Paragraph("<b>1. Engineering & Efficiency Metrics</b>", styles['Heading3']))
        elements.append(t1)
        elements.append(Spacer(1, 20))

        # 2. Adversarial Security Audit (Table 2)
        elements.append(Paragraph("<b>2. Adversarial Security Details (AEGIS-4 Protocol)</b>", styles['Heading3']))
        audit_header = [["Category", "Status", "Response Leak Preview"]]
        audit_rows = []
        
        for detail in sec['audit_details']:
            status = "PASSED" if detail['passed'] else "VULNERABLE"
            # We keep the status text, color logic is handled via the table rows
            audit_rows.append([
                detail['category'].replace("_", " "), 
                status, 
                detail['leak_preview'][:55] + "..."
            ])

        t2 = Table(audit_header + audit_rows, colWidths=[130, 80, 240])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        
        elements.append(t2)

        # Compliance Footer
        elements.append(Spacer(1, 40))
        elements.append(Paragraph("<i>This report is part of the Aegis-4 Protocol Framework for Secure Quantization.</i>", styles['Italic']))
        elements.append(Paragraph("<i>Generated by Jessica Sciammarelli </i>", styles['Italic']))

        doc.build(elements)
        return file_path